apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: generator
spec:
  image: alugand/flinkforst:1.0.0
  flinkVersion: v2_0
  flinkConfiguration:
    state.backend.type: "rocksdb"
    taskmanager.numberOfTaskSlots: "4"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
    podTemplate:
      spec:
        nodeSelector:
          tier: kafka
  taskManager:
    resource:
      memory: "2048m"
      cpu: 4
    podTemplate:
      spec:
        nodeSelector:
          tier: kafka
  job:
    jarURI: https://raw.githubusercontent.com/alugand/flink-justin/main/benchmarks/forst-benchmark/target/Generator.jar
    args:
      - "--src-rate"
      - "1000"
    parallelism: 4
