
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink
spec:
  image: alugand/flink:2.0.8
  flinkVersion: v2_0
  flinkConfiguration:

    taskmanager.numberOfTaskSlots: "4"
    state.backend.type: forst

    #state.backend.forst.cache.size-based-limit: "0"
    #state.backend.forst.cache.reserve-size: "0"

    execution.checkpointing.incremental: "true"
    execution.checkpointing.interval: "30s"
    execution.checkpointing.dir: "s3a://mybucket/flink-checkpoints/forst"
    s3.endpoint: "http://myminio-hl.minio-tenant:9000"
    s3.path.style.access: "true"
    s3.access-key: "minio"
    s3.secret-key: "minio123"

    metrics.reporters: prom
    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    web.submit.enable: "true"
    web.cancel.enable: "true"
    state.backend.forst.metrics.block-cache-usage: "true"
    state.backend.forst.metrics.block-cache-hit: "true"
    state.backend.forst.metrics.block-cache-miss: "true"
    state.backend.forst.metrics.bytes-read: "true"
    state.backend.forst.metrics.bytes-written: "true"
    state.backend.forst.metrics.column-family-as-variable: "true"
    state.backend.forst.metrics.compaction-pending: "true"
    state.backend.forst.metrics.compaction-read-bytes: "true"
    state.backend.forst.metrics.compaction-write-bytes: "true"
    state.backend.forst.metrics.cur-size-active-mem-table: "true"
    state.backend.forst.metrics.cur-size-all-mem-tables: "true"
    state.backend.forst.metrics.estimate-live-data-size: "true"
    state.backend.forst.metrics.estimate-num-keys: "true"
    state.backend.forst.metrics.estimate-pending-compaction-bytes: "true"
    state.backend.forst.metrics.estimate-table-readers-mem: "true"
    state.backend.forst.metrics.live-sst-files-size: "true"
    state.backend.forst.metrics.size-all-mem-tables: "true"
    state.backend.forst.metrics.total-sst-files-size: "true"

    state.backend.latency-track.keyed-state-enabled: "true"
    state.backend.forst.use-direct-writes: "true"
    state.backend.forst.use-direct-reads: "true"
  serviceAccount: flink
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
    spec:
      containers:
        # Do not change the main container name
        - name: flink-main-container
          ports:
            - containerPort: 9249
              name: prom
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 4
  job:
    jarURI: https://raw.githubusercontent.com/alugand/flink-justin/forst-benchmark/main/target/Update.jar
    parallelism: 4
