apiVersion: v1
kind: Secret
metadata:
  name: minio-prometheus-token
  namespace: minio-tenant
stringData:
  token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoibWluaW8iLCJleHAiOjQ5MDc1NTU1NDR9.MeNHW0yKSctQv9iTn6L2PpoJI20CSxt1IBvK4XFI6ustIf_t5eROnQcdhSzClECzBkv1UHyXtFIVAQorJsHCGA