apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flink-pod-monitor
  labels:
    release: prom
spec:
  podTargetLabels:
    - cluster
    - component
  selector:
    matchLabels:
      app: flink
  podMetricsEndpoints:
    - port: prom
      interval: 5s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-servicemonitor
  namespace: minio-tenant
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      v1.min.io/tenant: myminio
  namespaceSelector:
    matchNames:
    - minio-tenant
  endpoints:
  - port: http-minio
    path: /minio/v2/metrics/cluster
    scheme: http
    interval: 5s
    bearerTokenSecret:
      name: minio-prometheus-token
      key: token
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_name]
      action: keep
      regex: myminio-hl
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: instance
  - port: http-minio
    path: /minio/v2/metrics/bucket
    scheme: http
    interval: 5s
    bearerTokenSecret:
      name: minio-prometheus-token
      key: token
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_name]
      action: keep
      regex: myminio-hl
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: instance
  - port: http-minio
    path: /minio/v2/metrics/node
    scheme: http
    interval: 5s
    bearerTokenSecret:
      name: minio-prometheus-token
      key: token
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_name]
      action: keep
      regex: myminio-hl
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: instance
  - port: http-minio
    path: /minio/v2/metrics/resource
    scheme: http
    interval: 5s
    bearerTokenSecret:
      name: minio-prometheus-token
      key: token
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_name]
      action: keep
      regex: myminio-hl
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: instance