prometheus:
  service:
    type: NodePort
    nodePort: 30090
  prometheusSpec:
    nodeSelector:
      tier: manager
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector:
      matchNames:
      - manager
      - minio-tenant
grafana:
  service:
    type: NodePort
    nodePort: 30300
  nodeSelector:
    tier: manager
kube-state-metrics:
  nodeSelector:
    tier: manager